version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./web-client/public:/var/www
      - ./dev/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
  auth:
    build: ./auth-server
    volumes:
      - ./auth-server/app:/auth/app/
    #ports:
    #  - "3001:3000"
    expose:
      - "3000"
    depends_on:
      - db
      - nginx
    environment:
      DOMAIN: lip.local
      PORT: 3000
      CONFIG: ../config
      LOG_PATH: logs
      CORS_ORIGIN:
      ENCRYPTION_KEY: 5E884898DA28047151D0E56F8DC62927
      PRIVATE_KEY: .keys/jwtRS256.key
      PUBLIC_KEY: .keys/jwtRS256.key.pub
      ACCESS_TOKEN_EXP: 10
      REFRESH_TOKEN_EXP: 259200
      ISSUER: api.lip.local
    command: "node ."
    #command: /bin/sh
    #stdin_open: true
    #tty: true
  financial:
    build: ./financial-server
    volumes:
      - ./financial-server/app:/financial/app/
      - ./wait-for-postgres.sh:/financial/wait-for-postgres.sh
    #ports:
    #  - "3002:3000"
    expose:
      - "3000"
    depends_on:
      - db
      - nginx
    environment:
      PGUSER: $PG_USER
      PGPASSWORD: $PG_PWD
      PGDATABASE: $PG_DB
      PGHOST: db
    command: ["./wait-for-postgres.sh", "db", "--", "node", "."]
    #command: /bin/sh
    #stdin_open: true
    #tty: true
  db:
    image: postgres:alpine
    volumes:
      - ./financial-server/init.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PWD
      POSTGRES_DB: $PG_DB
      PGUSER: $PG_USER
      PGPASSWORD: $PG_PWD
      PGDATABASE: $PG_DB

